import Head from 'next/head';
import ImageSlider from '../components/image_slider';
import { useEffect } from 'react';
import { RootState } from 'lib/store/store';
import { useSelector, useDispatch } from 'react-redux';
import { activate } from 'lib/store/slices/main_nav_slice';

import Navbar from '../components/navbar';

export default function Home() {
  const links = useSelector((state: RootState) => state.main_nav);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(activate({}));
  });
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar links={links} />
      <ImageSlider />
    </>
  );
}
